services:
  - type: web
    name: event-api
    env: docker
    plan: standard
    buildCommand: ""
    startCommand: ""
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: GIN_MODE
        value: release
